version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.17.9
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
  kibana:
    image: kibana:7.17.9
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - "I18N_LOCALE=zh-CN"
  # logstash:
  #   image: logstash:7.17.9
  #   container_name: logstash
  #   ports:
  #     - 5044:5044
  #   depends_on:
  #     - elasticsearch
